POST {{scheme}}{{host}}:{{port}}/users
Accept: application/json
Content-Type: application/json

{
  "name": "Christian",
  "loyaltyPoints": 10,
  "settings": {
    "interests":["whisky", "cycling"]
  }
}

###

// Change user ID as needed.
// Note that all fields (except ID) need to be present.
PUT {{scheme}}{{host}}:{{port}}/users/0
Accept: application/json
Content-Type: application/json

{
  "name": "Christian",
  "loyaltyPoints": 100000,
  "settings": {
    "interests":["whisky", "cycling"]
  }
}

###

// Change user ID as needed.
GET {{scheme}}{{host}}:{{port}}/users/0

###
