# Note: if making requests to a running Docker container, use HTTP, not HTTPS.

GET {{scheme}}{{host}}:{{port}}/shoppingcart/123

###

POST {{scheme}}{{host}}:{{port}}/shoppingcart/123/items
Accept: application/json
Content-Type: application/json

[1, 2]

###

DELETE {{scheme}}{{host}}:{{port}}/shoppingcart/123/items
Accept: application/json
Content-Type: application/json

[1, 2]

###

GET {{scheme}}{{host}}:{{port}}/events?start=0&end=20
Accept: application/json

###
