GET {{scheme}}{{host}}:{{port}}/events?end=100

###

POST {{scheme}}{{host}}:{{port}}/offers
Accept: application/json
Content-Type: application/json

{
  "Description": "Nice deal"
}

###

GET {{scheme}}{{host}}:{{port}}/offers/0

###

PUT {{scheme}}{{host}}:{{port}}/offers/0
Accept: application/json
Content-Type: application/json

{
  "Description": "Best deal ever - JUST GOT BETTER"
}

###

DELETE {{scheme}}{{host}}:{{port}}/offers/0
