kind: Deployment
apiVersion: apps/v1
metadata:
  name: special-offers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: special-offers-pod
  template:
    metadata:
      labels:
        app: special-offers-pod
    spec:
      containers:
        - name: special-offers
          image: ejacobgshoppingcartregistry.azurecr.io/special-offers:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: special-offers
spec:
  selector:
    app: special-offers-pod
  ports:
    - port: 5002
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: special-offers-network-policy
spec:
  podSelector:
    matchLabels:
      app: special-offers-pod
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: loyalty-program-consumer
