# This deployment is very similar to the one outlined in shopping-cart.yaml.
kind: Deployment
apiVersion: apps/v1
metadata:
  name: loyalty-program
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-program
  template:
    metadata:
      labels:
        app: loyalty-program
    spec:
      containers:
        - name: loyalty-program
          image: ejacobgshoppingcartregistry.azurecr.io/loyalty-program:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            # Override the STARTUPDLL environment variable to control how the container starts up.
            - name: STARTUPDLL
              value: "api/LoyaltyProgram.dll"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: loyalty-program-consumer
spec:
  schedule: "*/1 * * * *" # Run once per minute.
  startingDeadlineSeconds: 30
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: loyalty-program
              image: ejacobgshoppingcartregistry.azurecr.io/loyalty-program:1.0.2
              imagePullPolicy: IfNotPresent
              env:
                - name: STARTUPDLL
                  value: "consumer/EventConsumer.dll"
          restartPolicy: Never
  concurrencyPolicy: Forbid # Only one copy should be running.
---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-program
spec:
  type: LoadBalancer
  ports:
    - name: loyalty-program
      port: 5001
      targetPort: 80
  selector:
    app: loyalty-program
